services:
  fastapi:
    build:
      context: ./fastapi
      dockerfile: Dockerfile
    container_name: fastapi
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - theatre-db
      - jaeger

  fastapi_auth:
    build:
      context: ./fastapi_auth
      dockerfile: Dockerfile
    container_name: fastapi_auth
    ports:
      - "8070:8000"
    env_file:
      - .env
    depends_on:
      - redis
      - theatre-db
      - jaeger

  redis:
    image: redislabs/redismod:latest
    container_name: redis
    expose:
      - "6379"
    restart: always
    volumes:
      - redis_data:/data

  elasticsearch:
    image: elasticsearch:8.7.0
    container_name: elasticsearch
    restart: always
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms200m -Xmx200m
    ports:
      - "9200:9200"

  nginx:
    image: nginx:latest
    container_name: nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/configs:/etc/nginx/conf.d:ro
    depends_on:
      - fastapi
      - fastapi_auth
    ports:
      - "80:80"

  theatre-db:
    image: postgres:16
    container_name: theatre-db
    ports:
      - "5432:5432"
    env_file:
      - .env
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:latest
    container_name: jaeger
    ports:
      - "14268:14268"
      - "16686:16686"

  tests:
    build:
      context: ./tests
      dockerfile: Dockerfile
    container_name: tests
    volumes:
      - ./tests:/opt/app/tests:ro
    environment:
      - POSTGRES_PASSWORD=qwerty1234
      - POSTGRES_USER=postgres
      - POSTGRES_DB=project_collection
    entrypoint: >
      sh -c "python3 functional/utils/wait_for_es.py
      && python3 functional/utils/wait_for_redis.py
      && python3 functional/utils/load_into_el.py
      && pytest -v
      && tail -f /dev/null"
    depends_on:
      - fastapi

volumes:
  postgres_data:
  elasticsearch:
  redis_data:
